### ISSUE TITLE
Use MultiShiftTrsm to compute eigenvectors of triangular matrix

### ISSUE THREAD

**Issue by poulson** [elemental/Elemental#100]
Elemental has all of the components necessary for computing the eigenvalue decomposition of a non-Hermitian matrix: there is support for a Schur decomposition and for a multi-shift Trsm. With these two routines combined, the eigenvectors of a triangular matrix can be computed and then rotated with the Schur vectors.

**Comment by jeffhammond** [comment]
Cool.  I look forward to this.

**Comment by poulson** [comment]
It's worth noting that the sequential functionality has been committed and leads to nearly a factor of two performance improvement in computing eigenvectors of general matrices (and about a 9x improvement in computing eigenvectors of triangular matrices).

**Comment by poulson** [comment]
A parallel version has been committed for some time now and matches LAPACK's output in our test cases (but performs several times faster).
