### ISSUE TITLE
QD and DD support

### ISSUE THREAD

**Issue by poulson** [elemental/Elemental#123]
Elemental's recently added recursive variant of the LLL for lattice reduction aggressively moves between a large family of arbitrary precision and native fixed-precision floating-point types in order to accelerate computation, but Elemental does not currently provide wrapper for either quad-doubles (`qd`) or double-doubles (`dd`), and so there are many circumstances where MPFR is used instead of what could be a quad-double, and `__float128` is used instead of what could be a double-double. Adding said wrappers would likely lead to a substantial performance improvement.

Additionally, Elemental would benefit from `qd` and `dd` versions of its sparse-direct solvers and Interior Point Methods.

But the looming issue is that `std::complex` cannot be used over `dd`, `qd`, or `BigFloat`.

**Comment by jeffhammond** [comment]
1) What implementation of `double double` are you using?  I don't see anything in the code about this.  I'm not sure how much faster `double double` will be than `__float128` unless you take special care to implement kernels that are vectorizable.

2) The complex type for 128b is supported by quadmath as `__complex128`.  See [quadmath.h](https://github.com/gcc-mirror/gcc/blob/master/libquadmath/quadmath.h) for verification.

I don't know if the Intel compiler supports this type or not, but it supported `complex _Quad ` in the past (https://software.intel.com/en-us/forums/intel-c-compiler/topic/289725).

**Comment by poulson** [comment]
@jeffhammond

The idea is to add support for the `dd` and `qd` classes from the QD package linked here:
http://crd-legacy.lbl.gov/~dhbailey/mpdist/
The same is done by the FPLLL package (https://github.com/dstehle/fplll).

Said operations are absolutely vectorizable (see, for example, http://homepages.math.uic.edu/~jan/mcs572/quad_double_cuda.pdf) since they boil down to native double-precision operations.

And, yes, `__complex128` exists, but the current definition of `El::Complex` is as a typedef of `std::complex`, so, at the very least, another layer of abstraction must be added there (though the regression need not be anywhere near as intrusive as Elemental's old complete reimplementation of `std::complex`). Complex versions of `mpfr_t` are an equivalently minor nuisance since the MPC package can be leveraged for the heavy lifting.

But, to my knowledge, there is not currently a publicly available complex extension of the `dd` and `qd` types.

**Comment by jeffhammond** [comment]
@poulson Ok.  I am familiar with Bailey's stuff.  Indeed, DD is vectorizable (@Maratyszcza has very nice work on this, which may be yet unpublished), but I don't know that the existing implementation in DD in Bailey's library is, which was the motivation for my comment.

**Comment by poulson** [comment]
As an update to this issue, Elemental has supported `DoubleDouble` and `QuadDouble` across the entire library (but there is not yet support for complex variants) for a week or two now.

**Comment by poulson** [comment]
@restrin and I have observed that there is a conflict between QD and MPICH 3.0.4 if `#include <mpi.h>` precedes `#include <qd/dd_real.h>` where the lower-order `double` for `dd_real` is of order `10^-20` times smaller than the higher-order `double` (instead of order `10^-16` times smaller). This is likely due to a symbol clash and does not appear to be an issue with MPICH 3.1.4 (the problem occurred within an Ubuntu VM on a Windows machine with an Intel Core i7). The net result of this bug is that Elemental would only achieve 16 digits of relative precision rather than ~30  or ~60 using `DoubleDouble` or `QuadDouble`.

**Comment by jeffhammond** [comment]
I'll try to investigate. I've been slowly trying to add quad support to
MPICH via F08.

On Monday, January 25, 2016, Jack Poulson <notifications@github.com> wrote:

> @restrin <https://github.com/restrin> and I have observed that there is a
> conflict between QD and MPICH 3.0.4 if #include <mpi.h> precedes #include
> <qd/dd_real.h> where the lower-order double for dd_real is of order 10^-20
> times smaller than the higher-order double (instead of order 10^-16 times
> smaller). This is likely due to a symbol clash and does not appear to be an
> issue with MPICH 3.1.4 (the problem occurred within an Ubuntu VM on a
> Windows machine with an Intel Core i7). The net result of this bug is that
> Elemental would only achieve 16 digits of relative precision rather than
> ~30 or ~60 using DoubleDouble or QuadDouble.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elemental/Elemental/issues/123#issuecomment-174698926>
> .
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by poulson** [comment]
@jeffhammond For what it's worth, I was unable to reproduce the bug in an Ubuntu 15.04 VM (with OS X 10.11 on Intel Core i7 host) with gcc 4.9.2 and a (manually-compiled) MPICH 3.0.4. @restrin has also mentioned that even compiling with `mpicc` (and not including `mpi.h`) is enough to trigger the bug. I'm now curious whether the host being Windows has anything to do with the bug (though I'm grasping at what the mechanism would be).

**Comment by jeffhammond** [comment]
Ok. Never mind. Windows sucks. MPICH is not supported there since MPICH2
1.4.1 or something like that. MPICH team rejects all Windows-related
correspondence with link to FAQ indicating it is unsupported.

MS-MPI is free. Intel MPI is not. Both support Windows and are MPICH based.

OpenMPI doesn't support Windows either AFAIK.

If this is a Linux VM on Windows, I apologize. Reading thread on phone
makes it hard to capture everything.

On Monday, January 25, 2016, Jack Poulson <notifications@github.com> wrote:

> @jeffhammond <https://github.com/jeffhammond> For what it's worth, I was
> unable to reproduce the bug in an Ubuntu 15.04 VM (with OS X 10.11 on Intel
> Core i7 host) with gcc 4.9.2 and a (manually-compiled) MPICH 3.0.4.
> @restrin <https://github.com/restrin> has also mentioned that even
> compiling with mpicc (and not including mpi.h) is enough to trigger the
> bug. I'm now curious whether the host being Windows has anything to do with
> the bug (though I'm grasping at what the mechanism would be).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elemental/Elemental/issues/123#issuecomment-174779035>
> .
>


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by poulson** [comment]
@jeffhammond @restrin I *think* the issue might be related to QD's `fpu_fix_start` and `fpu_fix_end` helper routines, which disable 80-bit internal floating-point precision, not having been called. I just committed a temporary fix, https://github.com/elemental/Elemental/commit/fc0ec9e03a6e3e11bed225d1c4f6b0d2c0005bfc, which seems to have the unfortunate side-effect of many double-precision routines only having ~14 decimal digits of relative accuracy instead of ~16.

I'm unsure of whether the cost of calling `fpu_fix_start` and `fpu_fix_end` at the beginning and end of every routine using QD would be prohibitive.

**Comment by poulson** [comment]
@restrin has verified that this fixes the issue for him. So there is now the open issue of how to properly toggle this fix to preserve the accuracy of double-precision computations.

**Comment by poulson** [comment]
Actually, I'm not so certain that I have observed an accuracy degradation from `fpu_fix_start`/`fpu_fix_end`. @restrin, could you let me know if you see a difference on your (apparently magically unique) machine?

**Comment by poulson** [comment]
This toggling issue was fixed months ago; currently, the significant feature missing for full QD and DD support is switching (back) away from Elemental's `Complex` class being a template alias to `std::complex`, which only supports `float`, `double`, and `long double` (with `__float128` being supported by GCC).

**Comment by poulson** [comment]
As of this commit, there is full `Complex<DoubleDouble>` and `Complex<QuadDouble>` support: https://github.com/elemental/Elemental/commit/4a33924fe57aacbe84a3bcf089dcffe034cb979e
