### ISSUE TITLE
Avoiding blocked Householder transformations when there are few right-hand sides

### ISSUE THREAD

**Issue by poulson** [elemental/Elemental#141]
@restrin noticed that Elemental's `ApplyPackedReflectors`, which is widely used throughout the library, is grossly inefficient when the assumption that there are large numbers of right-hand sides is violated (though it's worth noting that LAPACK uses the same algorithm within `xLARFB`). In particular, a simple analysis of the number of operations shows that the overhead of forming the triangular factor in the representation `I - V inv(T) V'` can dominate when there are O(1) right-hand sides, but is ignorable when there are O(n) right-hand sides. Switching to an unblocked algorithm based upon whether or not the number of right-hand sides meets some threshold (as a function of the matrix size) would be an easy win (and would also improve LAPACK).

**Comment by poulson** [comment]
After a long sequence of commits, `ApplyPackedReflectors` has much more descriptive comments, avoids several redistributions, and has full support for unblocked and blocked implementations (switching when the number of right-hand sides is greater than or equal to the blocksize).

**Comment by rhl-** [comment]
Awesome !
