### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by keithbriggs** [elemental/Elemental#142]
In several places in the code and docs, "Ricatti" should be "Riccati".

**Comment by poulson** [comment]
Thanks for pointing this out! I've fixed it in the code, but not yet in the docs (which are horribly out of date on all things optimization, lattice reduction, and sparse-direct solvers).
https://github.com/elemental/Elemental/commit/4c62afc6e91d5fadb939e58a24698505f76e6232
