### ISSUE TITLE
ElVars not setting external library include directory

### ISSUE THREAD

**Issue by restrin** [elemental/Elemental#143]
I installed the libraries GMP, MPFR, QD, MPC into a directory ~/InstallLib, then built Elemental using cmake as follows:

cmake .. -DCMAKE_INSTALL_PREFIX=~/Install-LLL -DCMAKE_BUILD_TYPE=Release -DEL_EXAMPLES=ON -DEL_TESTS=ON -DGMP_INCLUDES=~/InstallLib/include -DGMP_LIBRARIES=~/InstallLib/lib/libgmp.so -DMPFR_INCLUDES=~/InstallLib/include -DMPFR_LIBRARIES=~/InstallLib/lib/libmpfr.so -DQD_INCLUDES=~/InstallLib/include -DQD_LIBRARIES=~/InstallLib/lib/libqd.so  -DMPC_INCLUDES=~/InstallLib/include -DMPC_LIBRARIES=~/InstallLib/lib/libmpc.so

so that Elemental is installed into a separate folder. The corresponding config.h is attached (as .txt). After installation ElVars did not set the include directory for ~/InstallLib/include.

This was done on Ubuntu 14.04.1 LTS, using gcc/g++ 4.8.5.

[ElVars.txt](https://github.com/elemental/Elemental/files/262533/ElVars.txt)
[config.txt](https://github.com/elemental/Elemental/files/262531/config.txt)

**Comment by poulson** [comment]
Thanks for reporting this Ron! Could you confirm whether or not the above changeset fixes the issue?

**Comment by restrin** [comment]
Unfortunately, I still get the same issue, even though it seems that ElVars seems to have been updated with the correct include library. I've included ElVars and the Makefile I'm using. When I tried to compile, I still ended up getting the error:

/usr/bin/c++ -O3 -std=gnu++11  -fstack-protector -I/home/ron/Install-PDCO/include  -I/usr/include/mpich  -fstack-protector PDCODriverQP.cpp -o PDCODriverQP -L/home/ron/Install-PDCO/lib  -Wl,-Bsymbolic-functions  -Wl,-z,relro -lEl -lpmrrr -lElSuiteSparse -lpthread /home/ron/Install-PDCO/lib/libscalapack.so /home/ron/Install-PDCO/lib/libopenblas.so /usr/lib/gcc/x86_64-linux-gnu/4.8/libquadmath.so /home/ron/InstallLib/lib/libqd.so /home/ron/InstallLib/lib/libmpc.so /home/ron/InstallLib/lib/libmpfr.so /home/ron/InstallLib/lib/libgmp.so  /home/ron/Install-PDCO/lib/libscalapack.so /home/ron/Install-PDCO/lib/libopenblas.so /home/ron/Install-PDCO/lib/libparmetis.so /home/ron/Install-PDCO/lib/libmetis.so  /usr/lib/x86_64-linux-gnu/libmpichcxx.so /usr/lib/x86_64-linux-gnu/libmpich.so /usr/lib/x86_64-linux-gnu/libopa.so /usr/lib/x86_64-linux-gnu/libmpl.so /usr/lib/x86_64-linux-gnu/librt.so /usr/lib/libcr.so /usr/lib/x86_64-linux-gnu/libpthread.so
In file included from /home/ron/Install-PDCO/include/El/core.hpp:99:0,
                 from /home/ron/Install-PDCO/include/El.hpp:14,
                 from PDCODriverQP.cpp:1:
/home/ron/Install-PDCO/include/El/core/imports/mpc.hpp:13:17: fatal error: mpc.h: No such file or directory
 #include <mpc.h>
                 ^
compilation terminated.

[Makefile.txt](https://github.com/elemental/Elemental/files/264342/Makefile.txt)
[ElVars.txt](https://github.com/elemental/Elemental/files/264341/ElVars.txt)

**Comment by poulson** [comment]
Challenge: Figure it out :-)

**Comment by poulson** [comment]
Ah, the issue is that I did not ensure that the include directories were prefixed by "-I". This will require changing about 10 lines of code. A fix is imminent.

**Comment by poulson** [comment]
It should hopefully be fixed now!

**Comment by restrin** [comment]
Unfortunately, still not yet...it's quite odd. Looking at ElVars, it looks like the directory has been added, but ALL_MATH_INC wasn't updated correctly. I'm not too familiar with writing Makefiles, but just to make sure, does 1 == TRUE evaluate correctly in the Makefile?

The result from calling make was:
ron@ron-ICME:~/pdcoDriver$ make
/usr/bin/c++ -O3 -std=gnu++11  -fstack-protector -I/home/ron/Install-PDCO/include  -I/usr/include/mpich  -fstack-protector PDCODriverQP.cpp -o PDCODriverQP -L/home/ron/Install-PDCO/lib  -Wl,-Bsymbolic-functions  -Wl,-z,relro -lEl -lpmrrr -lElSuiteSparse -lpthread /home/ron/InstallLib/lib/libgmp.so  /home/ron/Install-PDCO/lib/libmetis.so  /usr/lib/x86_64-linux-gnu/libpthread.so
In file included from /home/ron/Install-PDCO/include/El/core.hpp:99:0,
                 from /home/ron/Install-PDCO/include/El.hpp:14,
                 from PDCODriverQP.cpp:1:
/home/ron/Install-PDCO/include/El/core/imports/mpc.hpp:13:17: fatal error: mpc.h: No such file or directory
 #include <mpc.h>
                 ^
compilation terminated.
make: *** [PDCODriverQP] Error 1


 
[ElVars.txt](https://github.com/elemental/Elemental/files/264685/ElVars.txt)

**Comment by restrin** [comment]
In fact the previous change seems to have done something bad since adding -I/home/ron/InstallLib/include manually results in the following error when calling make:

/usr/bin/ld: warning: libscalapack.so, needed by /home/ron/Install-PDCO/lib/libEl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopenblas.so.0, needed by /home/ron/Install-PDCO/lib/libEl.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libparmetis.so, needed by /home/ron/Install-PDCO/lib/libEl.so, not found (try using -rpath or -rpath-link)
/home/ron/Install-PDCO/lib/libEl.so: undefined reference to `zgemm_'
/home/ron/Install-PDCO/lib/libEl.so: undefined reference to `pclahqr_'
... (More undefined symbols)

To address the problem of the include file not being added, it seems that changing TRUE to 1 and using += instead of = ${ALL_MATH_INC} fixes the problem in ElVars.in, but that still results in the above errors (libscalapack.so and others not being included for some reason).

**Comment by poulson** [comment]
`ALL_MATH_INC` correctly contains `-I/home/ron/InstallLib/include` in the file that you sent, and `EL_COMPILE_FLAGS` is being set to contain `ALL_MATH_INC` as a subset. 

Are you sure that your makefile follows the convention demonstrated by the sandbox test driver: https://github.com/elemental/Elemental/blob/1f3aa6fdc219a62775dd60e628fef8338e83ce0c/sandbox/Makefile

**Comment by restrin** [comment]
I created a new Makefile that follows that convention but it results in the same error. I've included it here as well. It's resulting in the same error as before. Looking at the output of make, ALL_MATH_INC isn't containing -I/home/ron/InstallLib/include (it seems that 1 != TRUE for some reason).

When I changed it so that the resulting ElVars file looked like the attached one, the include directories were correctly set, but then I got the undefined reference problems (which I think are related to your most recent fix, since even my workaround from before of including directories explicitly results in the same problem).

[ElVars.txt](https://github.com/elemental/Elemental/files/264709/ElVars.txt)
[Makefile.txt](https://github.com/elemental/Elemental/files/264707/Makefile.txt)

**Comment by poulson** [comment]
What version of Make are you using (`make --version`)?

**Comment by restrin** [comment]
Make version 3.8.1

Is it too outdated?

**Comment by restrin** [comment]
Looking a bit more closely at the various ElVars included in this thread, it seems that ALL_MATH_LIB stopped including libscalapack.so, libopenblas.so and libmetis.so, which is causing the other errors when -I/home/ron/InstallLib/include is explicitly included.

**Comment by poulson** [comment]
Okay, I think that it should *finally* be fixed now!

**Comment by restrin** [comment]
Unfortunately, the problem of /home/ron/InstallLib/include not being included still remains. It seems that  ifeq(1, TRUE) is not being evaluated correctly (I tried changing it to ifeq(1,1), and it seemed to work after that, once I dealt with a recursive variable error).

**Comment by poulson** [comment]
Are you using GNU make? The makefile is generated by CMake.

**Comment by restrin** [comment]
Yes, running ```make --version``` gives me
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
```

**Comment by poulson** [comment]
I understand what happened now and the above fix should (heaven help us) finally resolve this issue.

**Comment by restrin** [comment]
I think it's almost there. I think GNU Make doesn't like the ``` ALL_MATH_INC = ${ALL_MATH_INC} ``` syntax, since it produces the error
``` /home/ron/Install-PDCO/conf/ElVars:19: *** Recursive variable `ALL_MATH_INC' references itself (eventually).  Stop. ```
I looked into this earlier, and I think that using += instead works, but I don't know whether this is acceptable syntax on other systems.

**Comment by restrin** [comment]
Also, is ElVars supposed to handle exporting the path of libqd.so.0? I noticed earlier that when compilation was successful (by manually adding the missing paths), that running the resulting binary complained that it couldn't find libqd.so.0, which I then exported manually afterwards (that never happened before).

**Comment by poulson** [comment]
I just added colons in the assignments, which hopefully fixes the issue you mentioned.

**Comment by restrin** [comment]
Success!

Thanks a lot Jack!
