### ISSUE TITLE
Using Gemm function in python

### ISSUE THREAD

**Issue by jomsdev** [elemental/Elemental#153]
I am trying to use the Gemm function in order to get A*B = C. The functions should take 7 or 8 arguments (the last one is "GEMM_DEFAULT" as default). 

However, when I run
``` python
# A, B & C are El.DistMatrix()
El.Gemm(El.NORMAL, El.NORMAL, 1.0, A, B, 0.0, C);
```
I get a TypeError: this function takes at least 8 arguments (7 given).

The problem is that the [binding](https://github.com/elemental/Elemental/blob/master/python/blas_like/level3.py#L37)  is calling always libEl.so with only 7 parameters. It seems that the variable argsAlg is totally useless and it could be solved changing 
``` python
args = [orientA,orientB,alpha,A.obj,B.obj,beta,C.obj, alg]
```

I forked elemental and did it. Now seems that all is working fine. I could do a pull request if you want.

If the problem was that I did something wrong with the API only let me know,

Thanks.

**Comment by poulson** [comment]
Hi Jordi, Thanks for finding this! The Python interface does not have a unit test framework like the C++ core does, so I guess I should not be surprised. I am away from a computer for the next couple of hours but can merge from my phone if you feel like submitting a PR.

All The Best,
Jack

**Comment by poulson** [comment]
I just submitted a fix that makes use of the intended argument list. Please let me know if this doesn't resolve the issue!
