### ISSUE TITLE
Produce Debian Packages

### ISSUE THREAD

**Issue by rhl-** [elemental/Elemental#174]
We would like to be able to package for Debian

**Comment by haimav** [comment]
Here is a patch that does this.
===================
commit 2a30147a5b0751c69f0567917f979503325ec8bb
Author: Yves Ineichen <yin@zurich.ibm.com>
Date:   Wed May 4 07:14:00 2016 +0000

    CMakeLists: deb package for Elemental (without dependencies)

    Based on 0eee0d8574d8542262155c3ef832ca3f180e3518

diff --git a/CMakeLists.txt b/CMakeLists.txt
index dfac693..d4d33a7 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -16,7 +16,8 @@ cmake_minimum_required(VERSION 2.8.12)

 project(Elemental C CXX)
 set(EL_VERSION_MAJOR 0)
-set(EL_VERSION_MINOR 86-dev)
+set(EL_VERSION_MINOR 86)
+set(EL_VERSION_PATCH 0)

 list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
 list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/modules")
@@ -629,6 +630,34 @@ set(CPACK_PACKAGE_VERSION_MINOR ${EL_VERSION_MINOR})
 set(CPACK_PACKAGE_DESCRIPTION_SUMMARY
   "Distributed-memory linear algebra and optimization")
 set(CPACK_PACKAGE_ICON "${CMAKE_SOURCE_DIR}/cmake/El.png")
+
+# Check the architecture (in case of debian distros)
+execute_process (
+  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
+  COMMAND dpkg --print-architecture
+  RESULT_VARIABLE GET_DPKG_ARCH
+  OUTPUT_VARIABLE DPKG_ARCH OUTPUT_STRIP_TRAILING_WHITESPACE
+)
+
+set(CPACK_GENERATOR "DEB")
+set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Jack Poulson <p@google.com>")
+set(CPACK_DEBIAN_PACKAGE_VERSION_MAJOR ${EL_VERSION_MAJOR})
+set(CPACK_DEBIAN_PACKAGE_VERSION_MINOR ${EL_VERSION_MINOR})
+set(CPACK_DEBIAN_PACKAGE_VERSION_PATCH ${EL_VERSION_PATCH})
+set(CPACK_DEBIAN_PACKAGE_VERSION
+       "${EL_VERSION_MAJOR}.${EL_VERSION_MINOR}.${EL_VERSION_PATCH}")
+set(CPACK_SYSTEM_NAME "${DPKG_ARCH}")
+set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "${DPKG_ARCH}")
+set(CPACK_PACKAGE_FILE_NAME
+       "${CPACK_PACKAGE_NAME}_${CPACK_DEBIAN_PACKAGE_VERSION}_${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}")
+
+set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.3.1-6), libgcc1 (>= 1:3.4.2-12), libgomp1, libopenblas-dev, liblapack-dev, python-numpy, libmetis-dev")
+if(HAVE_OMPI)
+  set(CPACK_DEBIAN_PACKAGE_DEPENDS "${CPACK_DEBIAN_PACKAGE_DEPENDS}, openmpi-bin, libopenmpi-dev")
+else()
+  set(CPACK_DEBIAN_PACKAGE_DEPENDS "${CPACK_DEBIAN_PACKAGE_DEPENDS}, mpich, libmpich-dev")
+endif()
+
 include(CPack)

 # ProjectConfig
diff --git a/cmake/configure_files/environment.py.in b/cmake/configure_files/environment.py.in
index 88ddff9..39c001f 100644
--- a/cmake/configure_files/environment.py.in
+++ b/cmake/configure_files/environment.py.in
@@ -10,7 +10,7 @@ import sys, ctypes
 import numpy as np
 from ctypes import pythonapi

-lib = ctypes.cdll.LoadLibrary("@CMAKE_INSTALL_PREFIX@/lib/@CMAKE_SHARED_LIBRARY_PREFIX@El@CMAKE_SHARED_LIBRARY_SUFFIX@")
+lib = ctypes.cdll.LoadLibrary("@CMAKE_SHARED_LIBRARY_PREFIX@El@CMAKE_SHARED_LIBRARY_SUFFIX@")

 # Environment
 # ===========

**Comment by haimav** [comment]
And here is a script to run it.
===================
git clone https://github.com/elemental/Elemental.git Elemental-deb
cd Elemental-deb
git checkout 71fce6e65c065e0b2f993435ca7524db7f54fa6f
git apply ElementalDeb.patch

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=./install -DEL_USE_64BIT_INTS=ON \
-DEL_HAVE_QUADMATH=OFF -DCMAKE_BUILD_TYPE=Release -DEL_HYBRID=ON \
-DBUILD_SHARED_LIBS=ON -DMATH_LIBS="-llapack -lopenblas -lm" \
-DINSTALL_PYTHON_PACKAGE=ON -DEL_DISABLE_VALGRIND=ON -DEL_DISABLE_PARMETIS=ON \
-DEL_DISABLE_SCALAPACK=ON -DCMAKE_RELEASE_POSTFIX="$MPI_SUFFIX" \
-DCMAKE_EXECUTABLE_SUFFIX="$MPI_SUFFIX" ../
make package -j 7

**Comment by rhl-** [comment]
Could you please submit this as a Pull Request so it may be reviewed?

**Comment by rhl-** [comment]
@haimav any progress? here? this should be an easy review.

**Comment by poulson** [comment]
FWIW, after having added an implementation of a distributed Aggressive Early Deflation Schur decomposition, there is no reason to need to include ScaLAPACK and it should be easier to handle Debian packages now. In the future I hope to implement a METIS replacement as well, but for now we could simply disable ParMETIS.

**Comment by rhl-** [comment]
I've created a branch to produce a debian package using the debian packaging tools: https://github.com/elemental/Elemental/commit/07babbc668882592374f324002e8a9e937fdbc66

I am not very knowledgeable about debian packaging, so, this thing I have created doesn't work properly, and the Elemental builds are too slow for me to experiment further without knowing what I am doing. However, it seems that you can usually more or less follow what we are doing with the RPM.

**Comment by jeffhammond** [comment]
@mbanck Are you willing to help here?  Elemental is an optional dependency of [MADNESS](https://github.com/m-a-d-n-e-s-s/madness/), [AQUARIUS](https://github.com/devinamatthews/aquarius), and perhaps others.  Thus, it might make your life easier with Debian chemistry packages.

**Comment by poulson** [comment]
@rhl- Was your preference to not use the CPack script?

**Comment by rhl-** [comment]
Yes, I would like Debian packages that we can push downstream to the Debian
repositories. They will assuredly reject anything based on CPack. However,
if someone wanted to also produce CPack it may be quicker. If someone who
knows how to use Debian packaging tools could finish my branch off that
would be ideal.

**Comment by poulson** [comment]
It is now fairly straightforward to produce experimental debian packages locally:
```
git clone https://github.com/elemental/Elemental.git elemental_0.87.orig
tar -czf elemental_0.87.orig.tar.gz elemental_0.87.orig
cd elemental_0.87.orig
pdebuild
```
The `make test` checks all pass for the (MPICH/gcc/python2) build, but I have not yet tried installing the package and testing the python installation. A few more tweaks might be needed.

**Comment by rhl-** [comment]
Once we get this into a PPA we should call this ticket done

**Comment by rhl-** [comment]
@poulson has produced the relevant packages 

See the release notes 

https://github.com/elemental/Elemental/releases/tag/v0.87
