### ISSUE TITLE
Implement Henry/Walker/Dongarra style Distributed Hessenberg QR

### ISSUE THREAD

**Issue by rhl-** [elemental/Elemental#176]
This will allow us to drop ScaLAPACK dependency which is a blocker for #174

**Comment by rhl-** [comment]
Achieved by #190

**Comment by poulson** [comment]
As a side note, the Henry/Walker/Dongarra approach chases one bulge per diagonal distribution block at a time and is a special case of the (now supported) multibulge implementation.
