### ISSUE TITLE
AxpyContract: buffer is not resized

### ISSUE THREAD

**Issue by davidsblom** [elemental/Elemental#178]
After a long search, I've found the problem for a very confusing floating point exception.

The `std::vector` `buffer` here
https://github.com/elemental/Elemental/blob/master/include/El/blas_like/level1/AxpyContract.hpp#L291
 
is not being resized to the correct value `sendSize` by the method `FastSize`. As a result, a floating point exception occurs in the MPI library (OpenMPI 1.10.3). 

I checked by outputting the size of the buffer at line 298.

```
std::cout << "buffer.size() = " << buffer.size() << std::endl;
```

and it is simply zero. When I changed line 291 to:

```
vector<T> buffer( sendSize );
```

the vector is correctly sized, and the floating point exception is solved.

So the vector's capacity is increased to numEntries, but I haven't figured out yet what the root cause is. I guess an implementation issue in the standard library, since with valgrind the problem did not occur, since the FastResize method called the resize method in the case.

compiler: gcc (Debian 4.9.2-10) 4.9.2

**Comment by davidsblom** [comment]
So, after a bit of thinking, my best guess is that due to the use of the `reserve` method, a number of elements are not initialized. And then, MPI is doing something with the uninitialized values resulting in a floating point exception. 

But this should not happen, since the buffer should be used fully. Unless there are some gaps in the data somehow.

**Comment by poulson** [comment]
Hi David,

Is there an example driver that reproduces this issue? Floating point exceptions should not be caused by additions  or multiplications, IIRC, so I am skeptical that it is occurring within the MPI call.

**Comment by poulson** [comment]
Giving this some more thought, it would seem to be possible (but highly unlikely) to generate a floating-point exception by adding two numbers and causing an overflow. So, perhaps `FastResize` is inappropriate for reduction operations.

**Comment by davidsblom** [comment]
I have tried to write a unit test for it, but it doesn't occur every time unfortunately. But for my simulation it always happens at the same point. the matrices are to big to print out on the terminal.

this is the error message:

```
[tud276993:02484] *** Process received signal ***
[tud276993:02484] Signal: Floating point exception (8)
[tud276993:02484] Signal code:  (-6)
[tud276993:02484] Failing at address: 0x3e8000009b4
[tud276993:02484] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7fc1513a08d0]
[tud276993:02484] [ 1] /lib/x86_64-linux-gnu/libpthread.so.0(raise+0x2b)[0x7fc1513a079b]
[tud276993:02484] [ 2] /lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7fc1513a08d0]
[tud276993:02484] [ 3] /home/davidblom/Apps/openmpi-1.10.3/install/lib/libmpi.so.12(+0x8cac0)[0x7fc151e5cac0]
[tud276993:02484] [ 4] /home/davidblom/Apps/openmpi-1.10.3/install/lib/openmpi/mca_coll_tuned.so(ompi_coll_tuned_reduce_generic+0x727)[0x7fc139c92107]
[tud276993:02484] [ 5] /home/davidblom/Apps/openmpi-1.10.3/install/lib/openmpi/mca_coll_tuned.so(ompi_coll_tuned_reduce_intra_pipeline+0xd6)[0x7fc139c92926]
[tud276993:02484] [ 6] /home/davidblom/Apps/openmpi-1.10.3/install/lib/openmpi/mca_coll_tuned.so(ompi_coll_tuned_reduce_intra_dec_fixed+0x136)[0x7fc139c85986]
[tud276993:02484] [ 7] /home/davidblom/Apps/openmpi-1.10.3/install/lib/libmpi.so.12(MPI_Reduce+0x1b2)[0x7fc151e3c5b2]
[tud276993:02484] [ 8] /home/davidblom/repositories/openfoam/foam-extend-3.2/lib/linux64GccLDPOpt/libEl.so(_ZN2El3mpi6ReduceIdvEEvPT_iNS0_2OpEiNS0_4CommE+0x15e)[0x7fc15fc5e76e]

```

**Comment by poulson** [comment]
I think the issue should be addressed now.

**Comment by davidsblom** [comment]
wow! thanks for the quick commit. I'll recompile and close the issue in case its resolved.

**Comment by davidsblom** [comment]
fixed it! thanks a lot.
