### ISSUE TITLE
Ensure that the Intel compilers respect floating-point evaluation orders

### ISSUE THREAD

**Issue by poulson** [elemental/Elemental#179]
The following bug in compiling LAPACK's secular equation solvers with Intel's compilers is extremely relevant to Elemental:
https://github.com/Reference-LAPACK/lapack/issues/43

In particular, it would appear from https://software.intel.com/en-us/forums/intel-c-compiler/topic/579190 that it is due to aggressive FMA optimizations. I do not think that GCC or Clang perform equivalent (dubious) optimizations.

@jeffhammond

**Comment by jeffhammond** [comment]
Does it appear with MKL or just Netlib LAPACK compiled with Intel compilers?  Just curious.

**Comment by jeffhammond** [comment]
I posted this on the LAPACK issue, but I am also copying it here explicitly.

[This page](https://software.intel.com/en-us/articles/consistency-of-floating-point-results-using-the-intel-compiler) discusses this in quite a bit of detail, including multiple pages on reassociation.  Reassociation is by default done for Fortran, C and C++, in spite of the violation of ISO/ANSI 

I attached the latest version of the PDF ([FP_Consistency_070816.pdf](https://github.com/Reference-LAPACK/lapack/files/456787/FP_Consistency_070816.pdf)), which was updated for version 17 of the Intel compilers.

There are both compiler flags and pragmas to control this behavior.

In case you are tempted to use `-fp-model precise`, that will turn off a whole host of optimizations of transcendentals and have a noticeable impact on performance for code that uses them heavily.

**Comment by poulson** [comment]
It would seem that `-fp-model precise -fp-model source` is the right set of flags to compile sensitive files with (e.g., Elemental's secular equation solvers) when using the Intel compilers on Linux. So it would seem that these source files should be separately handled in the CMake build.

**Comment by jeffhammond** [comment]
Alternatively, you could do it in the source code as described in the document I attached to https://github.com/Reference-LAPACK/lapack/issues/43#issuecomment-244949746.  This might make life easier from a CMake perspective.  It also ensures the code is handled correctly if some day there is another build system.

> For C and C++, the float_control pragma may be used to achieve the same effect as the switches /fp:precise and /fp:fast (-fp-model precise and -fp-model fast):
> #pragma float_control (precise, on) #pragma float_control (precise, off)
> Although such a pragma may be placed in front of an individual block of code, it applies to the entire containing function.

For example, you could do the following:
```c
#ifdef __INTEL_COMPILER
#pragma float_control (precise, on)
#pragma float_control (source, on)
#endif
```

I have not tested this, merely read the documentation...

**Comment by poulson** [comment]
I completely agree that is the better way to go!
