### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by haimav** [elemental/Elemental#180]
On mac I am getting many errors of the form:

/Users/haimav/Install/Elemental/include/El/lapack_like/spectral/CReflect.hpp: In function 'ElBidiagSVDCtrl_s El::CReflect(const El::BidiagSVDCtrl<float>&)':
/Users/haimav/Install/Elemental/include/El/lapack_like/spectral/CReflect.hpp:653:38: error: call of overloaded 'CReflect(const bool&)' is ambiguous
     ctrlC.useQR = CReflect(ctrl.useQR);

**Comment by jeffhammond** [comment]
Please provide full CMake invocation and compiler version details.

-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by poulson** [comment]
I will fix this in the next minute.

**Comment by poulson** [comment]
I would agree with Jeff that it is usually much easier to debug build issues with the CMake invocation, but, thankfully, this was a simple mistake on my part. `CReflect` is meant for converting between C++-specific and C-specific Elemental datatypes and should not have been called on a boolean in the first place. The default rule seems to have been fine on many compilers but should not be invoked.

**Comment by haimav** [comment]
Yes, I agree as well with Jeff, but specifically in this case I kind of already saw what the problem is and knew that someone who is familiar with the mechanism there will be able to solve it very quickly.

**Comment by poulson** [comment]
Is the issue fixed post commit https://github.com/elemental/Elemental/commit/780afa4b56ef10a7ed522a891ffb3c6cb2ceb153?

**Comment by haimav** [comment]
Yes. Closing the issue.

**Comment by haimav** [comment]
Similar issue popped up again with in lapack_like/spectral/CReflect.hpp at lines 45 and similar locations.

**Comment by poulson** [comment]
Thanks! I am frustrated that neither GCC with -Wall nor Clang on Ubuntu seems to pick up on this. It should be fixed now.
