### ISSUE TITLE
Read failing for large matrices

### ISSUE THREAD

**Issue by tjb900** [elemental/Elemental#191]
There are several places in io/Read/Binary.hpp and io/Read/BinaryFlat.hpp (at least), where stuff like this is done:

```
            const Int j = A.GlobalCol(jLoc);
            for( Int iLoc=0; iLoc<localHeight; ++iLoc )
            {
                const Int i = A.GlobalRow(iLoc);
                const Int localIndex = i+j*height;
                const std::streamoff pos = metaBytes + localIndex*sizeof(T);
```

Even though each process' chunk of the matrix is nice and manageable with 32-bit ints, this will overflow when setting localIndex since we are in fact creating an index into the global matrix.

I've patched this in my own use case just using some casts and it's working fine, but I'll be the first to admit it's ugly.  I'm happy to have a crack at doing it more nicely and submit a pull request if there's interest, but it seems like a pretty simple fix so I thought I'd just do this first.

Cheers,
Tim

**Comment by poulson** [comment]
Hi Tim, Elemental also supports building with 64-bit integers (`-D EL_USE_64BIT_INTS=ON`), which should also fix this issue. If you have any problems with the 64-bit integer build, please let us know!
