### ISSUE TITLE
Undefined reference

### ISSUE THREAD

**Issue by haimav** [elemental/Elemental#198]
With the 0.87 release, I am getting the following error when using Elemental:

CMakeFiles/skylark_krr.dir/skylark_krr.cpp.o: In function `void El::UpdateDiagonal<float, (El::DistNS::Dist)0, (El::DistNS::Dist)2>(El::DistMatrix<float, (El::DistNS::Dist)0, (El::DistNS::Dist)2, (El::DistWrapNS::DistWrap)0>&, float, El::ElementalMatrix<float> const&, long long)':
/usr/local/include/El/blas_like/level1/UpdateDiagonal.hpp:50: undefined reference to `void El::UpdateMappedDiagonal<float, float, (El::DistNS::Dist)0, (El::DistNS::Dist)2>(El::DistMatrix<float, (El::DistNS::Dist)0, (El::DistNS::Dist)2, (El::DistWrapNS::DistWrap)0>&, El::ElementalMatrix<float> const&, std::function<void (float&, float)>, long long)'
CMakeFiles/skylark_krr.dir/skylark_krr.cpp.o: In function `void El::UpdateDiagonal<double, (El::DistNS::Dist)0, (El::DistNS::Dist)2>(El::DistMatrix<double, (El::DistNS::Dist)0, (El::DistNS::Dist)2, (El::DistWrapNS::DistWrap)0>&, double, El::ElementalMatrix<double> const&, long long)':
/usr/local/include/El/blas_like/level1/UpdateDiagonal.hpp:50: undefined reference to `void El::UpdateMappedDiagonal<double, double, (El::DistNS::Dist)0, (El::DistNS::Dist)2>(El::DistMatrix<double, (El::DistNS::Dist)0, (El::DistNS::Dist)2, (El::DistWrapNS::DistWrap)0>&, El::ElementalMatrix<double> const&, std::function<void (double&, double)>, long long)'

**Comment by poulson** [comment]
Acknowledged. I will try to reproduce this thus evening.

**Comment by poulson** [comment]
Reproduced and locally fixed (the `include/El/blas_like/level1/decl.hpp` file had outdated prototypes). I am unsure of why this did not effect my Ubuntu GCC builds. I will push out 0.87.1 with this fix ASAP.

**Comment by poulson** [comment]
A fix has been pushed, xenial and yakkety builds have been pushed to the PPA, and 0.87.1 has been released: https://github.com/elemental/Elemental/releases/tag/v0.87.1

Thank you for reporting this issue (and I will continue to be disturbed that none of the CI's caught it).

**Comment by haimav** [comment]
FWIW this problem did not pop-up while compiling Elemental... only when I compiled libSkylark did this issue with Elemental crop up. So, since the CIs are only compiling Elemental they cannot catch it...

**Comment by rhl-** [comment]
Do we have a unit test for this?

**Comment by haimav** [comment]
No.
