### ISSUE TITLE
MPICH 3.2 + Clang 8.0 + OSX Sierra + MPI_Alltoallv = MPID_Request_create segfault

### ISSUE THREAD

**Issue by poulson** [elemental/Elemental#200]
My `lldb` session is showing a segfault within an `MPI_Alltoallv` call of the form
```
Process 67961 stopped
* thread #1: tid = 0x55d6af, 0x00000001040b70e3 libpmpi.12.dylib`MPID_Request_create + 275, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x00000001040b70e3 libpmpi.12.dylib`MPID_Request_create + 275
libpmpi.12.dylib`MPID_Request_create:
->  0x1040b70e3 <+275>: movaps %xmm0, 0x230(%rax)
    0x1040b70ea <+282>: movq   $0x0, 0x240(%rax)
    0x1040b70f5 <+293>: movl   $0x2c000000, 0x210(%rax)  ; imm = 0x2C000000 
    0x1040b70ff <+303>: popq   %rbp
```

This toolchain issue appears to be related to http://stackoverflow.com/questions/38155812/segmentation-fault-while-using-mpi-barrier-in-libpmpi-12-dylib

**Comment by jeffhammond** [comment]
See http://lists.mpich.org/pipermail/discuss/2016-May/004764.html and http://lists.mpich.org/pipermail/discuss/2016-August/004861.html for root cause analysis.

**Comment by poulson** [comment]
It seems that OS X alignment issues strike again.

**Comment by poulson** [comment]
I have confirmed that building Elemental using the git version of MPICH (compiling using clang) resolves the issue.
