### ISSUE TITLE
Build system not suited for packagers

### ISSUE THREAD

**Issue by stefanhusmann** [elemental/Elemental#201]
The build system seems to switch back and forth between build- and install steps. That is bad for packagers, who wish to build with user privilegues and only install with root privilegues. 

build function:
``` shell
build() {
  cd "${srcdir}/Elemental-${pkgver}"
  mkdir -p build && pushd build
  export DESTDIR=$pkgdir
  cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DINSTALL_PYTHON_PACKAGE=0 ..
  make
}
```
package function:
``` shell
package() {
  cd "${srcdir}/Elemental-${pkgver}/build"
  make install DESTDIR="$pkgdir"
  install -Dm644 ../LICENSE "$pkgdir"/usr/share/licenses/$pkgname/LICENSE
  # fix conflict with metis package
  rm "$pkgdir"/usr/include/metis.h "$pkgdir"/usr/lib/libmetis.so
}
```
Messages:
``` shell
 CleanUpAndExit:
 ^~~~~~~~~~~~~~
[ 97%] Building C object libparmetis/CMakeFiles/parmetis.dir/weird.c.o
[ 98%] Building C object libparmetis/CMakeFiles/parmetis.dir/wspace.c.o
[ 99%] Building C object libparmetis/CMakeFiles/parmetis.dir/xyzpart.c.o
[100%] Linking C shared library libparmetis.so
[100%] Built target parmetis
[  3%] Performing install step for 'project_parmetis'
[ 60%] Built target metis
[100%] Built target parmetis
Install the project...
-- Install configuration: ""
CMake Error at metis/libmetis/cmake_install.cmake:42 (file):
  file cannot create directory:
  /home/haawda/paketierung/meine_Pakete/elemental/pkg/elemental/usr/lib.
  Maybe need administrative privileges.
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)
```
See also https://github.com/elemental/Elemental/issues/8

**Comment by poulson** [comment]
It is unfortunately CMake's choice to require that (in general) the same level of privileges are required for the configure, make, and make install phases. While this is unconventional (and I dislike the choice as well), this has not posed any problem for building Debian or RHEL packages. Is this more than an aesthetic problem for you?

**Comment by stefanhusmann** [comment]
I maintain some cmake driven Packages for Arch Linux and not one of them requires me to have the same degree of privilegues in all steps. 
And to me this is not only an aestetic problem.

**Comment by poulson** [comment]
Please see the discussion on `ExternalProject_Add` here: http://public.kitware.com/pipermail/cmake/2013-July/055357.html

**Comment by poulson** [comment]
The need for privilege escalation in the `configure` and `make` stages will go away if no external dependencies are installed via `ExternalProject_Add`. My guess is that this is happening for Elemental's ParMETIS extensions (which are non-vital). You may want to simply sidestep this issue by configuring with the CMake option `-D EL_DISABLE_PARMETIS=ON` (assuming that BLAS, LAPACK, and METIS are already available).

**Comment by stefanhusmann** [comment]
That works (-D EL_DISABLE_PARMETIS=ON), and I get a package. But the paths for the .so files (/usr/lib64, should be /usr/lib) and the python files are wrong. Can I influence that?

**Comment by poulson** [comment]
I'm glad to hear it! And, yes, the install paths should be configurable via `CMAKE_INSTALL_LIBDIR` and friends: https://github.com/elemental/Elemental/blob/dca8750b06f398e2d4e9d6daed11b9979f217764/CMakeLists.txt#L70

**Comment by rhl-** [comment]
It seems there is no issue here warranting code change. I'm going to close this. If I am wrong please reopen.
