### ISSUE TITLE
Compilation error with 0.87.6

### ISSUE THREAD

**Issue by haimav** [elemental/Elemental#218]
See attached log. Using Ubuntu subsystem on windows (basically like compiling on a full Ubuntu).

[compile.txt](https://github.com/elemental/Elemental/files/749105/compile.txt)

**Comment by rhl-** [comment]
Can you provide a link to the full output of cmake so we can see your compile settings?

**Comment by haimav** [comment]
Sure here it is.
[cmake.txt](https://github.com/elemental/Elemental/files/749142/cmake.txt)

**Comment by haimav** [comment]
It seems this issue can be solved by making the parameter of eigMap be const Real & instead of just Real.
e.g.
        auto eigMap =
          [ctrl](const Real &gamma)
          { return (gamma+Sqrt(gamma*gamma+4*ctrl.rho))/(2*ctrl.rho); };

**Comment by poulson** [comment]
Hi Haim, yes, because `Real` can also be an object involving a heap allocation (e.g., `El::BigFloat`), it is useful to have functions accept `const Real&` where possible rather than passing by value so that unnecessary memory allocations can be avoided. 

Was this in your driver code?

**Comment by haimav** [comment]
@poulson No this is in your code in src/optimization/models/SparseInvCov.cpp

**Comment by poulson** [comment]
Acknowledged! Thank you; will fix this morning.

**Comment by haimav** [comment]
Will this be pushed in a 0.87.7 release? It is a compilation error that makes using 0.87.6 challenging.

**Comment by poulson** [comment]
Yes, good idea!

**Comment by poulson** [comment]
This should do it:
https://github.com/elemental/Elemental/releases/tag/v0.87.7

I'll push this to the website as well in a second.
