### ISSUE TITLE
Optimizing BLAS1-like routines

### ISSUE THREAD

**Issue by timmoon10** [elemental/Elemental#225]
I have been running numerical experiments with Axpy and I think we can significantly boost performance with some small changes. First, here are scaling studies with `float` and `Complex<double>`:
![axpy_scaling_float](https://cloud.githubusercontent.com/assets/4406448/24272315/ff5616a8-0fd9-11e7-8c0a-783a81f2c957.png)
![axpy_scaling_complexdouble](https://cloud.githubusercontent.com/assets/4406448/24272331/16c42bd6-0fda-11e7-8da1-1842c1f8a090.png)
These were performed on two 12-core Intel Xeon E5-2695v2 processors. I use OpenBLAS, compile with gcc-4.9.2 -O3, construct random square test matrices, and clear the L3 cache before each trial. Note that Elemental currently calls BLAS _axpy on matrix rows or columns, depending on the matrix dimensions, so tall and square matrices correspond to "BLAS (column-wise)" and fat matrices to "BLAS (row-wise)". My takeaways:

- For `float`, column-wise BLAS calls are much faster than row-wise. This is probably since column-wise calls can coalesce memory accesses. There is no significant difference for `Complex<double>`.
- A naive implementation with nested for loops will often outperform BLAS, especially with `Complex<double>`.
- More detailed profiling is required to determining when OpenMP vectorization improves upon the naive implementation.

I'm surprised that O3 optimized Axpy so often outperforms BLAS. Once the performance of Axpy is better understood, we should be able to apply similar optimizations to similar routines (Copy, Fill, Scale, Hadamard, Scale, Shift).

**Comment by poulson** [comment]
Thanks for the detailed experiments Tim! I am a bit confused by the second plot: are the "column-wise BLAS" and "Elemental" performance profiles underneath the "row-wise BLAS" one for `El::Complex<double>`? Also, how many threads were used in each of these cases?

**Comment by jeffhammond** [comment]
@timmoon10 BLAS1 operations are bandwidth limited.  Any decent compiler will generate the same or better code as BLAS1 in a library, but the compiler can inline and remove all of the unnecessary overhead required to use a library implementation.

**Comment by timmoon10** [comment]
@poulson My mistake, the second plot isn't very clear. Elemental's implementation and the BLAS implementations all achieve similar performance and max out at ~230 KFLOPS. There is not a significant difference between the column-wise and row-wise BLAS implementations.
