### ISSUE TITLE
Config.cmake QUAD bug

### ISSUE THREAD

**Issue by davydden** [elemental/Elemental#240]
when elemental is build without QD (i.e. `-DEL_DISABLE_QUAD:BOOL=True`),  `ElementalConfig.cmake` contains
```
set(Elemental_INCLUDE_DIRS "${Elemental_INCLUDE_DIRS};QD_INCLUDES-NOTFOUND")
```
which prevents it from using in any project:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
```
Probably `IF()` guard is missing around [this line](https://github.com/elemental/Elemental/blob/master/cmake/configure_files/ElementalConfig.cmake.in#L3).

**Comment by poulson** [comment]
It's a bit confusing, but the QD package is not related to `El::Quad`, as QD provides `El::DoubleDouble`, `El::QuadDouble`, and their complex variants; these are concatenations of double's to do higher-precision arithmetic using only `double`, but `El::Quad` is a genuine IEEE quad-precision type. If you had disabled QD (`EL_DISABLE_QD=ON`), then the error would have gone away, but, nevertheless, this is a bug, and my above (blind) commit should hopefully fix it.

**Comment by davydden** [comment]
I tried re-building from the `master` branch but `ElementalConfig.cmake` unfortunately still contains

```
set(Elemental_INCLUDE_DIRS "${Elemental_INCLUDE_DIRS};QD_INCLUDES-NOTFOUND")
```
which renders it unusable.

**Comment by davydden** [comment]
@poulson i misread you post, i think the problem is that you should guard [this line](set(Elemental_INCLUDE_DIRS "${Elemental_INCLUDE_DIRS};@QD_INCLUDES@")) in 
```
IF(QD_FOUND)
   
ENDIF()
```
as `QD` is only an optional dependency, AFAIK.

**Comment by poulson** [comment]
I am not at a personal computer for a while but would happily merge a changelist.
