### ISSUE TITLE
compiler warnings

### ISSUE THREAD

**Issue by davydden** [elemental/Elemental#243]
using `Elemental` shows compiler warnings
```
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/blas_like/level1/GetMappedDiagonal.hpp:30:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
     EL_PARALLEL_FOR
 ^
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/blas_like/level1/GetMappedDiagonal.hpp:75:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
         EL_PARALLEL_FOR
 ^
```
(and the same for `EL_PARALLEL_FOR` elsewhere).

Plus unused variables:
```
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/core/imports/choice.hpp:89:18: warning: unused parameter ‘os’ [-Wunused-parameter]
     virtual void HandleVersion( ostream& os=cout ) const { }
                  ^
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/core/imports/mpi_choice.hpp:49:18: warning: unused parameter ‘os’ [-Wunused-parameter]
     virtual void HandleVersion( ostream& os=cout ) const { }
                  ^
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/core/environment/decl.hpp:179:13: warning: unused parameter ‘os’ [-Wunused-parameter]
 inline void BuildStream( ostringstream& os ) { }
             ^
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/core/limits.hpp:250:23: warning: unused parameter ‘alpha’ [-Wunused-parameter]
 template<> inline int Lowest<int>( const int& alpha )
                       ^
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/core/Grid.hpp:145:13: warning: unused parameter ‘g1’ [-Wunused-parameter]
 inline void AssertSameGrids( const Grid& g1 ) { }
             ^
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/blas_like/level1/Round.hpp:30:13: warning: unused parameter ‘A’ [-Wunused-parameter]
 inline void Round( Matrix<Int>& A )
             ^
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/blas_like/level1/Round.hpp:35:13: warning: unused parameter ‘A’ [-Wunused-parameter]
 inline void Round( Matrix<BigInt>& A )
             ^
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/lapack_like/spectral.hpp:670:12: warning: unused parameter ‘n’ [-Wunused-parameter]
 inline Int NumShifts( Int n, Int winSize )
            ^
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/number_theory/MillerRabin.hpp:72:19: warning: unused variable ‘one’ [-Wunused-variable]
     const BigInt& one = BigIntOne();
                   ^
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/number_theory/MillerRabin.hpp:98:19: warning: unused variable ‘one’ [-Wunused-variable]
     const BigInt& one = BigIntOne();
                   ^
/linux-centos7-x86_64/gcc-4.8.5/elemental-0.87.7-6orlczncme6fkc4675dq5ca6lrlifbwr/include/El/number_theory/NextProbablePrime.hpp:18:13: warning: unused parameter ‘numReps’ [-Wunused-parameter]
 inline void NextProbablePrime( const BigInt& n, BigInt& nextPrime, Int numReps )
             ^
```

**Comment by jeffhammond** [comment]
`EL_PARALLEL_FOR` should have a guard for `#ifdef _OPENMP` around it, but the short-term solution is to compile with the `-fopenmp` flag.

I don't think unused variable warnings are worth fixing.

**Comment by poulson** [comment]
Historically I tried to always fix unused variable warnings, but the unused parameters in your examples are there for overloading reasons. The unguarded pragmas are a surprise to me; they should be guarded unless OpenMP was detected.

**Comment by davydden** [comment]
@jeffhammond :

> I don't think unused variable warnings are worth fixing.

IMO they are, as this appears in downstream projects. I would argue that most users would rather not have tens of lines of warning when compiling their code/library coming from `#include <El.hpp>`. 

@poulson :

> the unused parameters in your examples are there for overloading reasons

You just need to separate function declaration and implementation, i.e. 
```
virtual void HandleVersion( ostream& os=cout ) const { }
```
becomes
```
virtual void HandleVersion( ostream& os=cout ) const;
```
plus
```
void Args::HandleVersion( ostream&/*os*/) const 
{}
```
I have not looked at other places, but most likely they are the same.

**Comment by poulson** [comment]
For functions like complex-conjugation, one really does want the result to be a no-op for real input types, and overloading is the right way to go.

**Comment by davydden** [comment]
which of those warnings you are speaking about? I am not familiar with the codebase, I just saw the warnings and report them as I believe it's a good practice to avoid all compiler warnings and I am not aware of a case where it's impossible.

**Comment by jeffhammond** [comment]
@davydden I have at times tried to make warning-free code.  Based upon my experience, this impossible if you want to support more than one major release of a compiler.  Warnings come and go within major releases of GCC, and even if GCC and Clang behave the same, good luck realizing warning consistency with Intel, Cray, and IBM compilers.  This is less relevant to Elemental, because the only officially supported compilers are GCC and Clang (Intel 17.4+ is unofficially supported) but, in general, it is not a particularly productive aspiration for software developers, relative to all the other things they code be doing.

**Comment by davydden** [comment]
@jeffhammond the warnings we discuss here are quite easy to fix, as I said above, at least 4 out of 11 are the same.

**Comment by poulson** [comment]
I just pushed a simple changeset to avoid the two unused variable warnings (which only appear in `Release` builds, as the variable is used in `Debug` builds).

The unused parameter warnings are spurious and I don't follow how separating the declaration from the definition is supposed to avoid them; they would still be generated by the definition. If you want to put together a Pull Request that doesn't break anything and that fixes these warnings, please be my guest!

And the "unknown pragma" issue appears to be, as Jeff suggested, caused by a missing `-fopenmp` flag, which should be a separate issue. The pragma is only used when `omp.h` is included, and it appears that there is a problem with the CMake configuration.

**Comment by davydden** [comment]
> If you want to put together a Pull Request that doesn't break anything and that fixes these warnings

i will have a look
