### ISSUE TITLE
Could not determine BLAS format MacOS Sierra 10.12.6 v. 0.87.7

### ISSUE THREAD

**Issue by AndrejLischishin** [elemental/Elemental#247]
Hi there!
I know it is not a new issue, I've found something about it, but I still can't solve it, so I get the following error:

pptp-212-201-77-122:build_hybrid WhoAmI$ cmake -D CMAKE_INSTALL_PREFIX=/usr/local/elemental/0.87.7/HybridRelease -D CMAKE_BUILD_TYPE=HybridRelease -D CMAKE_CXX_COMPILER=/usr/local/bin/g++-7 -D CMAKE_C_COMPILER=/usr/local/bin/gcc-7 -D CMAKE_Fortran_COMPILER=/usr/local/bin/gfortran-7 -D MATH_LIBS="/usr/local/flame/libflame/lib/libflame.a;-framework Accelerate" -D ELEM_EXAMPLES=ON -D ELEM_TESTS=ON  ..
-- Appending /usr/local/elemental/Elemental-0.87.7/include for Elemental's source includes
-- Appending /usr/local/elemental/Elemental-0.87.7/build_hybrid/include for Elemental's binary includes
CMake Warning at CMakeLists.txt:286 (message):
  Build mode not specified, defaulting to Release build.

-- CXX11_COMPILER_FLAGS=-std=gnu++11
-- Using __restrict__ keyword.
-- Will parse MPI header /usr/local/Cellar/open-mpi/2.1.2/include/mpi.h
-- Using Open MPI version 2.1.2
-- Appending /usr/local/Cellar/open-mpi/2.1.2/include for MPI headers
-- Using prespecified OpenMP_C_FLAGS=-fopenmp
-- Using prespecified OpenMP_CXX_FLAGS=-fopenmp
-- Valgrind Prefix: 
-- Appending /usr/local/include for Valgrind headers
-- Will attempt to extend user-defined MATH_LIBS=/usr/local/flame/libflame/lib/libflame.a;-framework Accelerate
-- Testing for LAPACK support via Accelerate
-- Testing for LAPACK support via vecLib
-- A library with BLAS API found.
-- A library with LAPACK API found.
CMake Error at cmake/external_projects/ElMath.cmake:329 (message):
  Could not determine BLAS format.
Call Stack (most recent call first):
  CMakeLists.txt:434 (include)

-- Configuring incomplete, errors occurred!
See also "/usr/local/elemental/Elemental-0.87.7/build_hybrid/CMakeFiles/CMakeOutput.log".
See also "/usr/local/elemental/Elemental-0.87.7/build_hybrid/CMakeFiles/CMakeError.log".

Thanks!

**Comment by poulson** [comment]
Would you mind attaching your CMakeFiles/CMakeError.log?

**Comment by AndrejLischishin** [comment]
[CMakeOutput.log](https://github.com/elemental/Elemental/files/1405891/CMakeOutput.log)
[CMakeError.log](https://github.com/elemental/Elemental/files/1405892/CMakeError.log)

Sorry for delay

**Comment by AndrejLischishin** [comment]
I’ve tried to find something in both files, but didn’t get anywhere.

**Comment by poulson** [comment]
Hi Andrej, Sorry for the slow response. It appears that the libflame library you are specifying in MATH_LIBS doesn't exist.

**Comment by AndrejLischishin** [comment]
Ok, I'll try to fix it and respond as soon as possible, thank you, Jack!

**Comment by AndrejLischishin** [comment]
<img width="1047" alt="screen shot" src="https://user-images.githubusercontent.com/28063732/32069852-b82f37da-ba8a-11e7-8973-5b50beb84ba7.png">
Maybe I m missing something, but it should exist, so as you see, I can find it in finder and path to it, should be also correct

**Comment by poulson** [comment]
Your original CMake command was missing a `flame` subdirectory relative to the path in your image: make[1]: *** No rule to make target `/usr/local/libflame/lib/libflame.a'

Can you attach the new CMakeError.log?

**Comment by AndrejLischishin** [comment]
[CMakeOutput.log](https://github.com/elemental/Elemental/files/1419695/CMakeOutput.log)
[CMakeError.log](https://github.com/elemental/Elemental/files/1419696/CMakeError.log)

But this are the same, I didn't change anything from the moment I posted for the first time, maybe I should reinstall the libflame library?

**Comment by poulson** [comment]
My suspicion is that you didn't rm -rf your build directory before rerunning CMake with the corrected libflame path.

**Comment by AndrejLischishin** [comment]
This is a good point, I didn't remember to do this, I'll try to fix it now, thank you, Jack, and sorry for interruptions, I'll text as soon as it works or maybe I can't get further)

**Comment by AndrejLischishin** [comment]
I've tried to reinstall libflame, so now i have /usr/local/libflame, but I keep getting the same error:

pptp-212-201-77-122:libflame WhoAmI$ make install
Installing libflame-x86_64-5.1.0-36.a into /usr/local/libflame/lib/
Installing C header files into /usr/local/libflame/include-x86_64-5.1.0-36
Installing symlink libflame.a into /usr/local/libflame/lib/
Installing symlink include into /usr/local/libflame/
mv: include and /usr/local/libflame/include are identical
make: *** [/usr/local/libflame/include] Error 2

**Comment by poulson** [comment]
Firstly, I don't understand why you are reinstalling libflame. Secondly, that looks to be a libflame build system issue, so it would be better to post an issue to that project for it. Lastly, libflame doesn't lead to substantial performance increases with recent versions of El, so it would be easier to drop the dependency if its giving you so much trouble.

**Comment by AndrejLischishin** [comment]
I just was confused by this error message, but anyway, it seems now to work, thank you!
