### ISSUE TITLE
#include <omp.h> is missing if Elemental was build without EL_HYBRID

### ISSUE THREAD

**Issue by JM1** [elemental/Elemental#260]
Template functions Copy [1] and Zero [2] use OpenMP if the user's compiler does support OpenMP during header inclusion ('#ifdef _OPENMP'). But header omp.h is included only if EL_HYBRID was set when
Elemental was build ('#ifdef EL_HYBRID') [3].

[1] include/El/blas_like/level1/Copy.hpp
[2] include/El/blas_like/level1/Zero.hpp
[3] include/El/core/imports/omp.hpp

To fix this one could: 
1. always include omp.h if OpenMP is supported:
```
diff --git a/include/El/core/imports/omp.hpp b/include/El/core/imports/omp.hpp
index 2d8d551..93ca472 100644
--- a/include/El/core/imports/omp.hpp
+++ b/include/El/core/imports/omp.hpp
@@ -9,6 +9,10 @@
 #ifndef EL_IMPORTS_OMP_HPP
 #define EL_IMPORTS_OMP_HPP
 
+#ifdef _OPENMP
+# include <omp.h>
+#endif
+
 #ifdef EL_HYBRID
 # include <omp.h>
 # define EL_PARALLEL_FOR _Pragma("omp parallel for")
```
2. change `#ifdef _OPENMP` to e.g. `#ifdef EL_HYBRID` in [1] and [2]

**Comment by poulson** [comment]
Option 2 is definitely the correct fix for this (in the sense of preserving previous conventions). Thank you for noticing this!

Would you remind removing the option 1 rider in the MPI instantiation PR?

**Comment by JM1** [comment]
`#ifdef EL_HYBRID` or `#ifdef EL_HAVE_OPENMP`?

**Comment by poulson** [comment]
I think the former would be better.

**Comment by poulson** [comment]
Perfect!
