### ISSUE TITLE
Update Travis CI integration

### ISSUE THREAD

**Issue by JM1** [elemental/Elemental#262]
Elemental, as of now, is being built using GCC5 and Clang 3.8 on Travis CI (`.travis.yml`). To discover code/compiler bugs like #259 it might help to add newer compiler revisions, e.g. GCC8 and Clang 6.0. 

I would also suggest to remove `ccache` from `.travis.yml` because it does not speed up compilation. Actually it slows down compilation, e.g. [for GCC5 it is 45 Minutes incl. `ccache` vs. ~14 Minutes excl. `ccache`](https://travis-ci.org/JM1/Elemental/builds/411222468). 45 Minutes (excl. VM boot) is problematic, because Travis CI kills jobs that exceed the maximum time limit of 50 Minutes (incl. VM boot).

An updated `.travis.yml` for Elemental can be found [here](https://github.com/JM1/Elemental/compare/ec04d4aeac82...847adeeed090) ([build logs](https://travis-ci.org/JM1/Elemental/builds/411222468)). GCC8 fails to build Elemental because of #259 and the Clang 6.0 crashes during compilation. 

What do you think, @poulson ?

**Comment by jedbrown** [comment]
Looks like `CCACHE=yes` (and `CXX` is `/usr/lib/ccache/g++-5`) in both variants https://travis-ci.org/JM1/Elemental/jobs/411222469#L667.

**Comment by JM1** [comment]
Upps.. Thanks for spotting this bug! [New `.travis.yml` here](https://github.com/JM1/Elemental/compare/730d54ac9afb...942e5d8b2aea) ([build logs](https://travis-ci.org/JM1/Elemental/builds/411658101)). Actually `ccache` speeds up GCC builds (16 Minutes incl. ccache vs. >45 Minutes excl. ccache)..

**Comment by poulson** [comment]
That SGTM! And thank you for taking the time to look into this!

**Comment by jedbrown** [comment]
Looks like ccache is not being used for the Clang build. Is there a `/usr/lib/ccache/clang++` (without the version number)? Otherwise you can `CXX="ccache clang++-3.8"`.

**Comment by JM1** [comment]
ccache gives me a headache...

[According to `man cmake-properties`](https://manpages.debian.org/stretch/cmake-data/cmake-properties.7.en.html) both options `-DCMAKE_C_COMPILER_LAUNCHER=ccache` and `-DCMAKE_CXX_COMPILER_LAUNCHER=ccache` are supported e.g. by CMake 3.7, but it seems as if they have no effect on any *.ninja file or Makefile (at least for me). 

Setting environment variables CC/CXX (`export CC="ccache gcc"; export CXX="ccache g++"; cmake ...`) works but then CMake sets e.g. `CMAKE_C_COMPILER=/usr/bin/ccache` and drops the compiler binary from `CMAKE_C_COMPILER`. Same holds for `CMAKE_CXX_COMPILER`. This causes compilation problems e.g. for `cmake/external_projects/ElMath/OpenBLAS.cmake`:
```
[  0%] Performing build step for 'project_openblas'
/usr/bin/ccache: invalid option -- 'D'
Usage:
    ccache [options]
    ccache compiler [compiler options]
    compiler [compiler options]          (via symbolic link)

Options:
    -c, --cleanup         delete old files and recalculate size counters
                          (normally not needed as this is done automatically)
    -C, --clear           clear the cache completely (except configuration)
    -F, --max-files=N     set maximum number of files in cache to N (use 0 for
                          no limit)
    -M, --max-size=SIZE   set maximum size of cache to SIZE (use 0 for no
                          limit); available suffixes: k, M, G, T (decimal) and
                          Ki, Mi, Gi, Ti (binary); default suffix: G
    -o, --set-config=K=V  set configuration key K to value V
    -p, --print-config    print current configuration options
    -s, --show-stats      show statistics summary
    -z, --zero-stats      zero statistics counters

    -h, --help            print this help text
    -V, --version         print version and copyright information

See also <https://ccache.samba.org>.
make[4]: *** [Makefile.prebuild:42: getarch] Error 1
Makefile.system:899: Makefile.: No such file or directory
make[4]: *** No rule to make target 'Makefile.'.  Stop.
make[3]: *** [CMakeFiles/project_openblas.dir/build.make:112: download/OpenBLAS/build/stamp/project_openblas-build] Error 2
make[2]: *** [CMakeFiles/Makefile2:2368: CMakeFiles/project_openblas.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2380: CMakeFiles/project_openblas.dir/rule] Error 2
make: *** [Makefile:990: project_openblas] Error 2
```

If cmake is run with `-DCMAKE_C_COMPILER=ccache gcc` (`cmake -DCMAKE_C_COMPILER="ccache gcc" -DCMAKE_CXX_COMPILER="ccache g++" ...`) then cmake throws errors:
```
  CMake Error at CMakeLists.txt:24 (project):
    The CMAKE_C_COMPILER:
  
      /usr/bin/ccache gcc
  
    is not a full path to an existing compiler tool.
  
    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.
  
  -- Configuring incomplete, errors occurred!
```
Same holds for `CMAKE_CXX_COMPILER`.

On a Debian system `man ccache` suggests to just prepend `/usr/lib/ccache` to PATH, but this works only partially because [/usr/sbin/update-ccache-symlinks does not add versioned clang compilers, even removes those from `/usr/lib/ccache`](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867705). Manually adding those symlinks in `/usr/lib/ccache` somehow does not work for Clang compilers so far, but this is something I'm currently investigating..

**Comment by JM1** [comment]
Look at that: [`clang-3.8` is a symlink in `/usr/lib/ccache`](https://travis-ci.org/JM1/Elemental/jobs/412629274#L772) and [`/usr/lib/ccache` is the first entry in `PATH`](https://travis-ci.org/JM1/Elemental/jobs/412629274#L893). [But `echo $(which $CC)` still outputs `/usr/bin/clang-3.8`](https://travis-ci.org/JM1/Elemental/jobs/412629274#L903)?? Argh... why????

**Comment by JM1** [comment]
[Bingo!](https://github.com/JM1/Elemental/compare/6aaf3a4e94e4...caa8d20f0e4d) ([Build logs](https://travis-ci.org/JM1/Elemental/builds/413524363)). After `install:` is done, the newly created symlinks are gone, for whatever reason.. So by symlinking Clang in `before_script:` phase everything works as excepted. Any comments or suggestions about [the new `.travis.yml`](https://github.com/JM1/Elemental/compare/6aaf3a4e94e4...caa8d20f0e4d)?

**Comment by jeffhammond** [comment]
PRs were merged in 2018
