### ISSUE TITLE
dns expired for libelemental.org

### ISSUE THREAD

**Issue by tesch1** [elemental/Elemental#276]
now its some ad site...

**Comment by poulson** [comment]
Yea, I didn't feel like footing a $200 bill anymore. I need to update the GitHub to stop pointing there.

**Comment by jedbrown** [comment]
How is it a $200 bill?  It should be no more than $15/year for the .org
DNS.  Though it appears someone snatched it up thinking it was
accidentally expired so it isn't available now.

May as well put the docs site at libelemental.github.io?

**Comment by poulson** [comment]
I signed up god knows how many years ago and this was the bill yesterday. Please excuse me for not wanting to pay it anymore.

Moving to libelemental.github.io seems smart; the source code is available in the elemental-web repository.

![1And1Invoice](https://user-images.githubusercontent.com/129293/57557534-82c07000-7348-11e9-9366-a088364e9a97.png)

**Comment by jedbrown** [comment]
1&1 is shit.  The .org line was the DNS part ($20/year is still overchanging); the rest was hosting for 2 years.

**Comment by poulson** [comment]
I have updated the README: https://github.com/elemental/Elemental/blob/master/README.md
