### ISSUE TITLE
Old documentation no longer fully available

### ISSUE THREAD

**Issue by ernstbrunr51** [elemental/Elemental#277]
the documentation on core functionality leads to an error page, e.g.
https://elemental.github.io/documentation/dev/core/dist_matrix.html

Also the links for downloading the PDFs are no longer valid, e.g.
https://elemental.github.io/documentation/elem-dev.pdf

Could you please make them available again, or can I find the complete dev-doc somewhere else? Thank you!

**Comment by poulson** [comment]
Hi @ernstbrunr51 -- I stopped volunteering on this project a few years ago and no one stepped in, but a group at Lawrence Livermore did fork the project.

For what it's worth, you can find the source code for the documentation here: https://github.com/elemental/elemental-web/tree/master/source

**Comment by ernstbrunr51** [comment]
Thanks for the quick reply and help! I could build the full documentation from the source code you provided.
