### ISSUE TITLE
http://libelemental.org isn't a valid website "Nichts gefunden"

### ISSUE THREAD

**Issue by yurivict** [elemental/Elemental#278]

**Comment by ernstbrunr51** [comment]
read this:

https://github.com/elemental/Elemental/issues/276

**Comment by jeffhammond** [comment]
i removed references to libelemental.org from the github profile today.

**Comment by yurivict** [comment]
> i removed references to libelemental.org from the github profile today.

But this URL is still listed as the project's URL.

**Comment by jeffhammond** [comment]
I deleted it already but I guess I'll do it again.

**Comment by yurivict** [comment]
I don't know what might be wrong, but this URL is still displayed on the project page.

**Comment by jedbrown** [comment]
I think you're talking about the link in the right sidebar. I could see it, but deleted it now. I don't know if that's the same place Jeff tried.
