### ISSUE TITLE
How to get LU form of a DistMatrix ?

### ISSUE THREAD

**Issue by danghvu** [elemental/Elemental#28]
I try to print the matrix after Gaussian Elimination (source code in examples directory) but It does not give me the L or U form. 

Could you give some instructions on how to obtain the row echelon form out of a matrix?

Thanks

**Comment by poulson** [comment]
Several routines have "Explicit" factorization options which do what you're requesting, but I have apparently not added such a routine for LU yet. However, it is only a few lines of code:

    // Assuming that the scalar type is the field 'F'
    LU( A, p )
    auto L = A;
    auto U = A;
    MakeTriangular( LOWER, L ); FillDiagonal( L, F(1) );
    MakeTriangular( UPPER, U );
    // You may want to expand the permutation vector p via ExplicitPermutation

**Comment by danghvu** [comment]
Is `MakeTriangular` a new feature ? I couldn't find it in the master branch, can't compile with it.
Does `FillDiagonal` perform transformation ? I check the code and It seems to just setting the value..

**Comment by poulson** [comment]
My apologies. ``MakeTriangular`` was recently made obsolete. Please use ``MakeTrapezoidal`` instead (which is more general, but, if used as above, performs the same operation as the old ``MakeTriangular`` routine).

The current documentation is temporarily out-of-date due to recent rapid feature development for 0.86.

**Comment by danghvu** [comment]
Thanks, that works ! Is there any equivalent LU for DistSparseMatrix ?

**Comment by poulson** [comment]
Not at this point, but, perhaps surprisingly, there are a large number of (for at least another week) undocumented convex optimization solvers which accept general sparse distributed matrices (e.g., Least Absolute Value regression, Chebyshev points, Dantzig selectors, Basis pursuit, Basis pursuit denoising / LASSO, and soft-margin Support Vector Machines).

**Comment by poulson** [comment]
The routine ``LinearSolve`` (formerly ``GaussianElimination``) has been extended to sparse matrices via a "primal-dual" embedding ``[I A^H; A 0] [x; y] = [0; b]``.
