### ISSUE TITLE
MPICH2 on Travis fails to detect MPI_Reduce_scatter

### ISSUE THREAD

**Issue by jiahao** [elemental/Elemental#42]
Travis consistently fails to build MPICH2 on Ubuntu precise.

[Packages installed](https://travis-ci.org/jiahao/Elemental/jobs/57515943#L616): libmpich2-3 libmpich2-dev 1.4.1-ubuntu1

[Error message:](https://travis-ci.org/jiahao/Elemental/jobs/57515943#L723): "Could not find MPI_Reduce_scatter"

**Comment by jeffhammond** [comment]
What is the actual error message?  (Side note: this is one my major pet peeves with CMake - that it doesn't inline the actual error but rather forces a human to dig for it.)

**Comment by jiahao** [comment]
Finding the actual error took way longer than I had anticipated.

[Error log](https://travis-ci.org/jiahao/Elemental/jobs/57525578#L794):

```
/usr/bin/clang-3.7     -DCHECK_FUNCTION_EXISTS=MPI_Reduce_scatter   -Wl,-Bsymbolic-functions  -Wl,-z,relro    CMakeFiles/cmTryCompileExec1234559794.dir/CheckFunctionExists.c.o  -o cmTryCompileExec1234559794 -rdynamic -lmpichcxx -lmpich -lopa -lmpl -lrt -lcr -lpthread 
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../libmpichcxx.so: undefined reference to `operator delete[](void*)'
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../libmpichcxx.so: undefined reference to `operator new(unsigned long)'
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../libmpichcxx.so: undefined reference to `operator delete(void*)'
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../libmpichcxx.so: undefined reference to `operator new[](unsigned long)'
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../libmpichcxx.so: undefined reference to `__cxa_pure_virtual'
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../libmpichcxx.so: undefined reference to `__cxa_allocate_exception'
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../libmpichcxx.so: undefined reference to `__gxx_personality_v0'
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../libmpichcxx.so: undefined reference to `__cxa_throw'
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../libmpichcxx.so: undefined reference to `vtable for __cxxabiv1::__class_type_info'
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../libmpichcxx.so: undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've never seen this before. Is this a C++ compiler version mismatch with the `libmpichcxx` in `mpich2`?

**Comment by jeffhammond** [comment]
Ubuntu packages are almost certainly built with GCC.  You need to either use GCC for your C++ compiler or use Clang for your MPICH build.  Or disable C++ altogether, given that Elemental uses only the C bindings.  One way to do this is to not try to link against libmpichcxx.so, but I do not know how to tell CMake that.

**Comment by jiahao** [comment]
Confirming that using the gcc compiler on Travis fixes the problem.

Removed from CI configuration matrix in 6b604dbe9609761802073c96a055e2c801220bc4
