### ISSUE TITLE
Redesign CMAKE_BUILD_TYPE

### ISSUE THREAD

**Issue by jiahao** [elemental/Elemental#43]
1. `CMAKE_BUILD_TYPE` is overridden from its default CMake meaning but the help text is not changed. The default values like `RelWithDebInfo` are no longer valid.

2. Changing `CMAKE_BUILD_TYPE` does not automatically refresh `C_FLAGS`, `CXX_FLAGS` and `Fortran_FLAGS`, even if the flags fields are cleared.

3. Is there any reason why `Pure` (MPI only) vs `Hybrid` (MPI+OpenMP) cannot be handled in a different variable like `USE_OPENMP`? The CMAKE_BUILD_TYPEs are really meant to just distinguish between release and debug builds.

**Comment by poulson** [comment]
I believe that I just fixed (1) and (3): https://github.com/elemental/Elemental/commit/b0fae8f1f43661592d5a79140251be36be47bfbb

**Comment by poulson** [comment]
I think that (2) should not be expected to be supported as, to the best of my knowledge, the best practice for changing the build type is to wipe the build directory and reconfigure. (I'm not a fan of the need for an ``rm -rf *`` but I believe that it's standard.)
