### ISSUE TITLE
No metis

### ISSUE THREAD

**Issue by horrovac** [elemental/Elemental#51]
You did not include metis in the Elemental 0.86, Release Candidate 1 Zip/Tar archive, cmake fails with no useful error message. All tests pass and then it reports failure to configure. That cost me a day of troubleshooting.

**Comment by poulson** [comment]
Thank you for raising this issue.

The tarball and zip are autogenerated by GitHub. It would appear that GitHub chooses not to include the source of git submodules in these bundles. I will make sure to avoid letting GitHub link to these in future releases (the production release of 0.86 will be very soon and will undergo significantly more testing).

**Comment by poulson** [comment]
For what it's worth, several people have had this concern before: https://github.com/wbond/package_control/issues/126#issuecomment-5470380
