### ISSUE TITLE
CMake ExternalProject for ScaLAPACK

### ISSUE THREAD

**Issue by poulson** [elemental/Elemental#57]
While ScaLAPACK can optionally be used for a few purposes in Elemental (with a full interface being a useful goal), there is not yet an automatic way of downloading/building/installing ScaLAPACK, despite the fact that ScaLAPACK has a CMakeLists.txt

**Comment by dpo** [comment]
It would also be great to link against an external ScaLAPACK.

**Comment by poulson** [comment]
@dpo That is currently already supported automatically if ScaLAPACK support is detected in MATH_LIBS. And, should I create similar interfaces to ScaLAPACK as for OpenBLAS/METIS/ParMETIS, there would be external detection first before attempting to manually build (with an option for the user to avoid external detection and force a build).

**Comment by dpo** [comment]
Excellent, thanks. I didn't realize I could stick Scalapack in MATH_LIBS.

**Comment by poulson** [comment]
ScaLAPACK is now automatically handled as well through the combination of ``find_library`` and ``ExternalProject_Add``: https://github.com/elemental/Elemental/commit/b9a16e7d4312afe3a43df6dddf3c6f66c042a7ba
