### ISSUE TITLE
OSX RPATH not being set correctly for CMake external project shared libraries

### ISSUE THREAD

**Issue by jakebolewski** [elemental/Elemental#61]

**Comment by poulson** [comment]
Ugh. I think I'm going to have to buy a Mac to reliably handle this.

**Comment by justusc** [comment]
Join the dark side of the force!

**Comment by poulson** [comment]
I'm flying dark on this one, but hopefully this changeset fixes the issue for metis and parmetis: https://github.com/elemental/Elemental/commit/8a75f38c2b45e4037e2c4843b5f6ad73c1d0a917

**Comment by poulson** [comment]
I closed since @jakebolewski claims that the issue is now fixed for him.
