### ISSUE TITLE
Automatically installing MPICH

### ISSUE THREAD

**Issue by poulson** [elemental/Elemental#64]
It would seem that a number of users would find it convenient for Elemental to automatically download and install MPICH if no pre-installed version of MPI was detected during configuration. 

I've done a bit of legwork to help move towards this capability:
    https://github.com/elemental/Elemental/commit/ae457c55fcd2ce0544b08c20f86f26a738ae00e3
but CMake's `ExternalProject_Add` causes external dependencies to be built during the "make", as opposed to "configure" phase, and the MPI link and compilation flags must be known at configuration time. Thus, we must have some way of specifying these parameters a priori, which is troubling. Perhaps it's worth looking into how PETSc handles this dependency, as I'm under the impression that PETSc will download and install MPICH by default. @jedbrown

**Comment by jedbrown** [comment]
PETSc will download and install it if the user passes `--download-mpich`. We don't use CMake.

**Comment by poulson** [comment]
@jedbrown I'm aware of that. I mean that PETSc likely has some way of detecting the appropriate compiler flags. Unless the approach is to install MPICH, run ``mpicc``, and parse the flags?

**Comment by jedbrown** [comment]
We install it, then detect it like a normal MPI (typically using `mpicc`).  Anything else is asking for a maintenance disaster.
