### ISSUE TITLE
ElVars file does not have the libraries in the expected format

### ISSUE THREAD

**Issue by rocanale** [elemental/Elemental#67]
My auto generated ElVars file contains the following in ALL_MATH_LIBS field:

```
ALL_MATH_LIBS = -lEl -lpmrrr  \
                 /usr/local/El/lib/libopenblas.so gfortran pthread m /usr/lib/gcc/x86_64-linux-gnu/4.8/libquadmath.so  \
                 /usr/local/El/lib/libparmetis.so /usr/local/El/lib/libmetis.so
```
As you can see `gfortran pthread m` are written instead of `-lgfortran -lpthread -lm`. I tried to fix it by myself but without success.

Platform used:
* Linux Mint 17.1 (Ubuntu 14.04)
* gcc 4.8.2
* cmake 2.8.12.2

**Comment by poulson** [comment]
Finding the full path to gfortran is surprisingly difficult in CMake: see the following discussion that I had on the subject in 2011 
    http://www.cmake.org/pipermail/cmake/2011-January/042390.html

The essential difficulty is that libgfortran is typically installed with revision numbers such as libgfortran.so.3, but libgfortran.so is almost never installed. Thus, the CMake developers claim that users should not expect to be able to link against gfortran.

**Comment by rocanale** [comment]
I did a small fix, maybe it is not the optimal solution but it sets the right linker flags.
https://github.com/elemental/Elemental/pull/68/commits

**Comment by rhl-** [comment]
this appears to be resolved.
