### ISSUE TITLE
Creating Mac OS X packages

### ISSUE THREAD

**Issue by poulson** [elemental/Elemental#69]
While Elemental now has preliminary support for CPack, it seems that CPack still assumes the existence of ``PackageMaker`` which has moved beyond deprecation and is now non-functional on recent versions of Mac OS X. So the choices seem to be:

1. Wait for CPack to add support for ``productbuild``
2. Manually add support for ``productbuild`` (I do not like this option), or
3. Hook into another system entirely, such as hashdist or anaconda.

**Comment by tkelman** [comment]
Homebrew-science is providing binaries of Elemental, I imagine that serves most users' needs pretty well? https://github.com/Homebrew/homebrew-science/blob/master/elemental.rb

**Comment by poulson** [comment]
In this case, it is time to update homebrew to make sure that it points to the dev version.

**Comment by rhl-** [comment]
this is a duplicate of #9
