### ISSUE TITLE
factorize MPI and other external interfaces into separate project

### ISSUE THREAD

**Issue by jeffhammond** [elemental/Elemental#7]
This feature was discussed on the email list.  I am adding it as an issue to avoid losing it.

Jack:

```
As for the length of core/imports/mpi.cpp: I agree that the file is
quite large. I think that it would be a great idea if
core/imports/{blas,lapack,mpi} were their own project, which Elemental
simply included, as I would expect them to see wider use and more
contributions. Keeping all three together would be a good idea for
issues like large integer support, as Elemental will not really be able
to effectively use 64-bit MPI buffers without 64-bit integers for
BLAS/LAPACK, and vice versa.

What do you think about moving core/imports/{blas,lapack,mpi} into an
external project and including them as git submodules in Elemental?
```

Jeff:

```
If {blas,lapack,mpi} wrappers are split off, it will be key to have API versioning 
so El can query to see if they match up.

I would be inclined to add BLIS, Eigen and LAPACK C support (aren't there 
two variants of this?) as part of this refactoring, if only so I could avoid 
Fortran 77 altogether.
```

The first step in this project will be to create new repos in the Elemental team space.

**Comment by rhl-** [comment]
@jeffhammond  any progress here? this would presumably also help speedup the El build, even if only incrementally.

**Comment by jeffhammond** [comment]
@rhl- No.  It never reached high enough priority since nothing was blocked on it and my life got significantly more hectic after June 2014.

If you want to get something started by pulling out the code into a separate GitHub project, I'll certainly try to help you hack on it.

**Comment by jeffhammond** [comment]
I haven't looked at either in a while, but @patflick also has a C++ MPI wrapper called [MXX](https://patflick.github.io/mxx/) that might have similar features.  I wonder if there is any way to join forces somehow, since Pat has done a bunch of really nice software quality work on that project.

**Comment by poulson** [comment]
I thumbed through MXX and am impressed by the level of software engineering. Also, MXX includes a sample sort implementation, which is sorely needed in Elemental. It would be important that there could continue to be support for blocking and non-blocking communication with BigFloat and I haven't yet had to time to see how easy that would be to support.

**Comment by patflick** [comment]
Hi guys,
I'd be happy to help out if you decide to make use of my project.
However, before you decide, a few caveats:
- mxx requires at least C++11, and I'm not planning on supporting earlier standards. 
- I'm still messing around with possible implementations (API decisions) for non-blocking communication. I wanted to implement it as something similar to std::future (mxx::future), but not all use cases are good for this. I.e, at this moment there is no stable API for non-blocking.
- In general (not only non-blocking comm), i'm still introducing major changes every now and then, so I wouldn't call this a stable API as of yet.

Do you have a list of features that would be needed?
Regarding custom data types (BigFloat, etc), those should be pretty easy to add. I may need to write some documentation about that though. *"I'll add the documentation later"* hasn't really come to fruition yet... :-D

**Comment by poulson** [comment]
@patflick Thankfully Elemental also requires C++11, so the first item is not a problem.

As for non-blocking communication: essentially only `ISend` and `IRecv` support is required. Elemental handles non-blocking calls for types that require serialization by extending the wrapper for the  `MPI_Request` to own the buffer (and to free it after the request is complete).

I'm not sure what type of features you're curious about, but Elemental actively uses the vast majority of the routines from https://github.com/elemental/Elemental/blob/master/src/core/imports/mpi.cpp and https://github.com/elemental/Elemental/blob/master/src/core/mpi_register.cpp.
