### ISSUE TITLE
Compile error with VS2013

### ISSUE THREAD

**Issue by skn123** [elemental/Elemental#73]
4>f:\gitsources\elemental\include\El/core/types.hpp(235): error C2146: syntax error : missing ';' before identifier 'Dist'

**Comment by poulson** [comment]
Elemental makes use of a number of features (such as ``constexpr``) which are not supported by current versions of Visual Studio. However, VS2015 should contain sufficient support, and so the next version of Elemental after the VS2015 release should properly compile with VS.
