### ISSUE TITLE
Full Python MPI interface

### ISSUE THREAD

**Issue by poulson** [elemental/Elemental#76]
It would be beneficial to extend Elemental's Python interface to support MPI wrappers, as there is currently very minimal MPI support. This might be best accomplished via CMake running regular expressions on `mpi.h` in order to extract the various constants (perhaps based upon whether MPICH, OpenMPI, or MS-MPI was detected).

**Comment by jeffhammond** [comment]
I'm curious why mpi4py doesn't work here. Can you explain?

**Comment by poulson** [comment]
@jeffhammond For one, Elemental registers many of its one types (e.g., Quad, Complex<Quad>, and various pairings of index and scalar types); it's not clear to me how I could avoid needing to wrap these types. Also, for some operations, such as reductions, Elemental branches between three different MPI routines; using mpi4py would loose such performance and correctness safeguards.

**Comment by jedbrown** [comment]
Maybe @dalcinl can comment on types.
As for branching, can you give an example? It seems overkill to roll an entire set of Python MPI wrappers in order to abstract the implementation.

**Comment by poulson** [comment]
@jedbrown As an example of a non-trivial wrapper: 
https://github.com/elemental/Elemental/blob/695ec4174726ff38c5f7443c836b1be988a7946d/src/core/imports/mpi.cpp#L1837

And here are the custom datatypes and reduce operations:
https://github.com/elemental/Elemental/blob/695ec4174726ff38c5f7443c836b1be988a7946d/src/core/mpi_register.cpp

Honestly, the one annoyance (other than resolving whether or not ``MPI_Comm``, ``MPI_Group``, etc. are void pointers or integers) is pulling in constants such as ``MPI_COMM_WORLD`` and ``MPI_SUM`` from the header file (which I think should be done with simple regexes based upon the detected MPI type; I believe mpi4py does something similar). I've previously used regexes on the MPI headers to determine the version number of OpenMPI.

**Comment by dalcinl** [comment]
If you have an MPI datatype defined in C, then it is rather trivial to expose it in Python as an ``mpi4py.MPI.Datatype`` instance. @poulson Could you please point me to some code where I can figure out your needs?

**Comment by dalcinl** [comment]
* About parsing a real ``mpi.h``, that is going to be a mess. That's not the approach I use, I rather defined all the MPI constants and calls to be consumed in Cython code: https://bitbucket.org/mpi4py/mpi4py/src/master/src/include/mpi4py/libmpi.pxd . Then, when needed (eg. running configure tests to catch missing MPI calls), I parse that file.

* IIUC, to wrap your ``ReduceScatter()`` routine, you first need to pass Python array data (NumPy?, memoryview?), then the ``Op`` and ``Comm`` handles, they are easy to extract from the Python instances (using C/API calls). 

* The custom ``Datatype`` and ``Op`` handles are trivial to expose (using a mpi4py C/API call) as instances of mpi4py's corresponding types.

Executive example, pure C: https://bitbucket.org/mpi4py/mpi4py/src/master/demo/wrap-c/helloworld.c

What are you currently using to wrap Elemental's API in Python?

**Comment by poulson** [comment]
@dalcinl Thanks for the detailed response! I don't currently have Cython as a dependency of Elemental; would it be as straightforward to expose the wrappers without it?

I'm currently using manual ctypes code to expose the interfaces (having scrapped a previous SWIG interface for many reasons). The folder containing the python interface is here:
    https://github.com/elemental/Elemental/tree/695ec4174726ff38c5f7443c836b1be988a7946d/python
and the (small number of) MPI wrappers are here:
    https://github.com/elemental/Elemental/blob/695ec4174726ff38c5f7443c836b1be988a7946d/python/core/imports/mpi.py

**Comment by dalcinl** [comment]
``ctypes`` example handling the ``int``/``void*`` mess: https://bitbucket.org/mpi4py/mpi4py/src/master/demo/wrap-ctypes/

But you should switch to ``cffi``: http://cffi.readthedocs.org/ . I have a complete reimplementation of ``mpi4py`` based on ``cffi`` (no yet public), so I can assert ``cffi`` is a quite capable tool.

**Comment by poulson** [comment]
@dalcinl Thanks; I'm currently handling the ``int``/``void*`` issue through a simple C routine which returns ``sizeof`` of each of the relevant MPI types (I assume that mpi4py does something similar).

What are your reasons for suggesting the switch to cffi? Avoiding manual prototypes? Part of the reason I may keep the current interface is that my C interface has to avoid any generic functions, so a C++ routine such as ``QP``, which might accept arguments of types ``Matrix``, ``DistMatrix``, ``SparseMatrix``, and ``DistSparseMatrix``, with underlying scalars of types ``float``, ``double``, ``Complex<float>``, and ``Complex<double>``, must become sixteen different C routines, such as ``ElQPDistSparse_z``, which might take in a ``DistSparseMatrix<Complex<double>>``. When I construct my Python interface, I then roll all of these flattened interfaces back into a single generic ``QP`` interface. I am doubtful that cffi would handle that automatically (and this is significantly more code than manually typing the prototype information).

But, with that said, if there is a significant performance difference, then I still think it would be worth looking into.

**Comment by dalcinl** [comment]
To summarize: You can go back and forth (C/C++/Fortran)/MPI <-> Python/mpi4py using plain C/C++ code, boost::python, SWIG, Cython, ctypes, cffi, f2py, so pick you favorite tool (just look at the many ``demo/wrap-*`` examples in mpi4py's  repo). But again, take a look at ``cffi``, you are an experienced C/C++ programmer, ``cffi`` will look quite natural to you (however, it is mostly C-like, no C++).

**Comment by jedbrown** [comment]
As an aside, it's not clear to me why a C caller _wants_ a type-level distinction between `Matrix`, `DistMatrix`, `SparseMatrix`, and `DistSparseMatrix`.  Hell, even in C++ I find the type-level distinction gets in the way when trying to write comparison code or anything that dynamically chooses.

**Comment by dalcinl** [comment]
@poulson ``cffi`` is ``ctypes``-like, but much nicer to work with.

**Comment by poulson** [comment]
@jedbrown I'd be happy to discuss that issue in detail, though it would be a bit out of place here. If you want to open another issue I'll readily discuss.
