### ISSUE TITLE
FindElemental.cmake

### ISSUE THREAD

**Issue by poulson** [elemental/Elemental#78]
It is standard for CMake-based packages to provide a "Find" script for other CMake projects to locate previous installations, i.e., ``FindElemental.cmake``. Elemental should provide such a script in order to help simplify its demanding build system.

**Comment by jedbrown** [comment]
As a CMake project, you would normally provide ElementalConfig.cmake.  A FindElemental.cmake script would typically only be needed (and distributed independently) if Elemental was not build using CMake and did not provide ElementalConfig.cmake.

http://www.cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file

**Comment by poulson** [comment]
Thanks, that's a great point Jed. I should have known better.

**Comment by justusc** [comment]
Users can use `find_package(Elemental)` if the configure script is available.
The configure script can also include a targets file, which defines cmake interface libraries that makes linking easier. So users could:
```
$ cmake -D Elemental_ROOT_DIR=/path/to/elemental ...
```
CMakeLists.txt:
```
find_package(Elemental HINTS ${Elemental_ROOT_DIR})
target_link_library(myapp Elemental)
```

**Comment by poulson** [comment]
I have just merged the following PR from @YingzhouLi 
https://github.com/elemental/Elemental/pull/80
