### ISSUE TITLE
add autotools build system

### ISSUE THREAD

**Issue by jeffhammond** [elemental/Elemental#8]
Some users and packagers may prefer autotools to cmake.

**Comment by stefanhusmann** [comment]
Yes, especially if the given cmake build system is broken. It does not honor DESTDIR settings.
```
-- Installing: /usr/lib/libmetis.so
CMake Error at metis/libmetis/cmake_install.cmake:42 (file):
  file INSTALL cannot copy file
  "/home/haawda/paketierung/meine_Pakete/elemental/src/Elemental-0.87.3/build/download/parmetis/build/metis/libmetis/libmetis.so"
  to "/usr/lib/libmetis.so".
Call Stack (most recent call first):
  cmake_install.cmake:37 (include)
```

**Comment by poulson** [comment]
@stefanhusmann This appears to be due to `ExternalProject_Add` requiring `DESTDIR` to be manually propagated. This should be a one-liner for `ParMETIS`, `METIS`, and `LAPACK` since those external projects use CMake. But OpenBLAS and BLIS may require more care.

**Comment by poulson** [comment]
@stefanhusmann Did you export `DESTDIR` as an environment variable before running `cmake`? If so, would you mind opening an issue for this particular problem?

**Comment by stefanhusmann** [comment]
I only passed DESTDIR to the make command, not to the cmake command, and not exported. I will check and report back.
